http.host: 0.0.0.0

transport.host: 0.0.0.0

discovery.zen.minimum_master_nodes: 1

http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/

path.repo: ["/usr/share/elasticsearch/snapshot"]